spring.application.name=smart-erp

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?sslmode=${DB_SSL:disable}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}